name: Create Branch, Append Line, Commit, and Create PR

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Name of the branch to create'
        required: true

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create new branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b ${{ github.event.inputs.branch-name }}

      - name: Append line to README.md
        run: echo "This is a new line added by GitHub Actions." >> readme.md

      - name: Commit changes
        run: |
          git add readme.md
          git commit -m "Append line to readme.md"

      - name: Push changes
        run: git push origin ${{ github.event.inputs.branch-name }}
